# Generated by Django 6.1 on 2026-09-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True, help_text="ссылка на платеж", max_length=800, null=True
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True, help_text="укажите ID сессии", max_length=200, null=True
            ),
        ),
    ]
